# Generated by Django 5.0.3 on 2024-03-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zing_it', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='wasif',
            new_name='name',
        ),
    ]
